<?php
/**
 * @category BaseAction
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 16/3/15 14:05
 * @since
 */
namespace common\core\base;

use common\core\session\GSession;
use yii\base\Action;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;
use yii\web\Request;
use yii\web\Response;

/**
 * Class BaseAction
 * @package common\core\base
 */
class BaseAction extends Action
{
    public $method = null;
    public $responseType = 'json';
    /**
     * @var array
     */
    protected $responseTypes = ['html', 'raw', 'json', 'jsonp', 'xml'];
    /**
     * @var Request
     */
    public $request;

    public function init()
    {
        $this->request = \Yii::$app->request;
        if(in_array($this->responseType, $this->responseTypes)){
            \Yii::$app->response->format = $this->responseType;
        } else{
            \Yii::$app->response->format = Response::FORMAT_HTML;
        }
        if($this->method != null && $this->request->method != strtoupper($this->method)){
            throw new HttpException(403, '请求方式不正确');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function render($params = [])
    {
        return $this->renderPage($this->id, $params);
    }

    /**
     * @param $page
     * @param $params
     * @return string
     */
    public function renderPage($page, $params = [])
    {
        GSession::set('current', $this->getUniqueId());
        GSession::set('pathinfo', $this->request->getPathInfo());
        $params = ArrayHelper::merge(['request' => $this->request, 'selfurl' => $this->getUniqueId(), 'selfUrl' => $this->getUniqueId()], $params);

        return $this->controller->render(strtolower($page), $params);
    }
}
