<?php
/**
 * @category BaseController
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 2016/9/20 15:47
 * @since
 */
namespace common\core\base;

use common\core\session\GSession;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Request;

/**
 * Class BaseController
 * @package common\core\base
 */
class BaseController extends Controller
{
    public $method = null;
    /**
     * @var Request
     */
    public $request;

    public function init()
    {
        $this->request = \Yii::$app->request;
        if(defined('IN_ROOT') && IN_ROOT === true){
            Yii::setAlias('web',Yii::getAlias('@web/'.APP_NAME));
            Yii::setAlias('webroot',Yii::getAlias('@webroot/'.APP_NAME));
        }
        if($this->method != null && \Yii::$app->request->method != strtoupper($this->method)){
            //这里可以处理方式不一样的操作,便于快捷判断
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 为了偷懒，这里有改动，同时兼容原来的
     * @param string $page
     * @param array $params
     * @return string
     */
    public function render($page = null, $params = [])
    {
        if(is_array($page)){
            $params += $page;
        }
        return $this->renderPage((is_string($page) ? $page : $this->action->id), $params);
    }

    /**
     * @param $page
     * @param $params
     * @return string
     */
    public function renderPage($page, $params = [])
    {
        GSession::set('current', $this->getUniqueId());
        GSession::set('pathinfo', $this->request->getPathInfo());
        $params = ArrayHelper::merge(['request' => $this->request, 'selfurl' => $this->getUniqueId(), 'selfUrl' => $this->getUniqueId()], $params);

        return parent::render(strtolower($page), $params);
    }
}
