<?php
/**
 * @category WwwBaseAction
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 2016/10/1 23:16
 * @since
 */

namespace application\web\www\components;

use application\web\www\WwwUser;
use common\core\base\BaseAction;
use qiqi\helper\WechatHelper;
use yii\helpers\ArrayHelper;

/**
 * Class WwwBaseAction
 * @package application\web\www\components
 */
class WwwBaseAction extends BaseAction
{
    public $responseType = 'html';
    /**
     * @var WwwUser
     */
    protected $account;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->account = \Yii::$app->getUser()
                                   ->getIdentity();
    }

    /**
     * @param array $params
     * @return string
     */
    public function render($params = [])
    {
        return $this->renderPage($this->id, ArrayHelper::merge($params, [
            'account' => $this->account,
            // 'wechat'=>WechatHelper::getApp()
        ]));
    }
}
