<?php
/**
 * @category WwwBaseAction
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 2016/10/1 23:16
 * @since
 */

namespace application\web\www\components;

use common\core\base\BaseAction;

/**
 * Class WwwBaseAction
 * @package application\web\www\components
 */
class WwwBaseAction extends BaseAction
{
    public $responseType = 'html';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
