<?php
/**
 * @category ApiBaseController
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 2017/5/8 09:04
 * @since
 */

namespace application\web\api\components;

use common\core\base\BaseController;

/**
 * Class ApiBaseController
 * @package application\web\api\components
 */
class ApiBaseController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->response->format = 'json';
        if($this->isAllowed()){
            // 允许 fizzday.net 发起的跨域请求
            header("Access-Control-Allow-Origin: fizzday.net");

            //如果需要设置允许所有域名发起的跨域请求，可以使用通配符 *
            header("Access-Control-Allow-Origin: *");
        }
    }

    protected function isAllowed(){
        return true;
    }
}
