<?php
/**
 * @category AdminBaseAction
 * @author   gouki <gouki.xiao@gmail.com>
 * @created 2016/10/1 23:15
 * @since
 */
namespace application\web\admin\components;

use application\web\admin\AdminUser;
use common\core\base\BaseAction;
use yii\helpers\ArrayHelper;

/**
 * Class AdminBaseAction
 * @package application\web\admin\components
 */
class AdminBaseAction extends BaseAction
{
    /** @var AdminUser $userinfo */
    public $userinfo;
    public $responseType = 'html';

    public function init()
    {
        // $this->userinfo = \Yii::$app->getUser()
        //                             ->getIdentity();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $page
     * @param $params
     * @return string
     */
    public function renderPage($page, $params = [])
    {
        $params = ArrayHelper::merge([
            'request'  => $this->request,
            'selfurl'  => $this->getUniqueId(),
            'selfUrl'  => $this->getUniqueId(),
            'userinfo' => $this->userinfo,
            'self'     => $this,
        ], $params);
        $params += $this->request->get();
        return $this->controller->render(strtolower($page), $params);
    }
}
